version: 0.9.2.{build}
image: Visual Studio 2017


environment:
  matrix:
    - PlatformToolset: v140_xp

platform:
    - x64
    - x86

configuration:
    - Release
    - Debug

install:
    - if "%platform%"=="x64" set archi=amd64
    - if "%platform%"=="x86" set archi=x86
    - call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" %archi%
    - nuget restore "%APPVEYOR_BUILD_FOLDER%"\NppMenuSearch\packages.config -PackagesDirectory "%APPVEYOR_BUILD_FOLDER%"\packages


build:
    parallel: true                  # enable MSBuild parallel builds
    verbosity: minimal

build_script:
    - cd "%APPVEYOR_BUILD_FOLDER%"
    - msbuild NppMenuSearch.sln /m /p:configuration="%configuration%" /p:platform="%platform%" /p:PlatformToolset="%PlatformToolset%" /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"

after_build:
    - cd "%APPVEYOR_BUILD_FOLDER%"\NppMenuSearch\bin\
    - ps: >-
        Set-Location -Path $env:PLATFORM\$env:CONFIGURATION
        
        if ($env:CONFIGURATION -eq "Release") {
            $ZipFileName = "NppMenuSearch_$($env:APPVEYOR_REPO_TAG_NAME)_$($env:PLATFORM).zip"
            7z a $ZipFileName NppMenuSearch.dll
            Push-AppveyorArtifact $ZipFileName -DeploymentName releases
        }

deploy:
    provider: GitHub
    auth_token:
        secure: i7NPJkceDL6AEsutHPmbQIUMwAHptcW5b6AEYV7NpILvPhg0mBDApZgqTFhKv73G
    artifact: releases
    draft: false
    prerelease: false
    force_update: true
    on:
        appveyor_repo_tag: true
        PlatformToolset: v140_xp
        configuration: Release
